// GENERATED by scripts/generate-rules.ts — do not edit by hand.
// Derived from data/ticket-corpus.json: 350 resolved support tickets.
//
// Method: tickets clustered by resolution action; for each cluster above the
// frequency threshold (14 tickets = 4%), a detector was emitted for the
// account-state condition present at contact time. baseScore is measured, not
// chosen: P(this was the reason for contact | the state is present).
// Variant phrasings are mined from ticket subject/body text per cluster,
// keeping cluster-distinctive phrases — which is where the circumlocutions
// ("boily thing", "water thing", "took money twice") come from.
//
// Clusters below threshold — no detector emitted:
//   other:honoured promo retroactively as : 7 tickets
//   other:updated shipping address before : 6 tickets
//   other:emailed pdf invoice: 6 tickets
//   other:sent manual reset link: 9 tickets
//
// Emitted clusters:
//   wrong_item: 112 of 350 tickets; state present in 160; P(reason | state) = 0.7 · e.g. "arrived broken", "not what i ordered", "item broken"
//   late_delivery: 72 of 350 tickets; state present in 90; P(reason | state) = 0.8 · e.g. "where is my order", "package not here", "delivery?"
//   duplicate_charge: 54 of 350 tickets; state present in 60; P(reason | state) = 0.9 · e.g. "two charges same day", "charged twice", "two charges same day"
//   refund_pending: 45 of 350 tickets; state present in 60; P(reason | state) = 0.75 · e.g. "refund not receved", "money not back", "refund not received"
//   unexpected_renewal: 39 of 350 tickets; state present in 65; P(reason | state) = 0.6 · e.g. "it took money again", "subsription charged again", "subscription charged again"

import type { AccountState, Charge, Hypothesis, Order } from "./types";
import { money, shortDate, daysAgo, gapText } from "./format";

export const GENERATED = true;

const HOUR = 3_600_000;
const DAY = 86_400_000;

/** lowercase item-name tokens, so live account items always match themselves */
function itemTokens(order: Order): string[] {
  return order.items.flatMap((i) => {
    const plain = i.name.split(",")[0].toLowerCase();
    return [plain, ...plain.split(/\s+/)];
  });
}

/** "Ceramic kettle, 1.7L" → "ceramic kettle", for mid-sentence use. */
function plainName(order: Order): string {
  return order.items[0]?.name.split(",")[0].toLowerCase() ?? "your item";
}

export function generateHypotheses(state: AccountState): Hypothesis[] {
  const out: Hypothesis[] = [];
  const now = Date.now();

  // duplicate_charge — 54 of 350 tickets; state present in 60; P(reason | state) = 0.9
  // Gap threshold 60 min: max observed same-amount gap in cluster was 55 min.
  // Chronological pairing: each charge pairs with the nearest earlier
  // same-amount charge in the window — N same charges → N−1 unique hypotheses.
  {
    const ok = state.charges
      .filter((c) => c.status === "succeeded")
      .slice()
      .sort((x, y) => x.createdAt.getTime() - y.createdAt.getTime());
    for (let i = 1; i < ok.length; i++) {
      const later: Charge = ok[i];
      const a = ok
        .slice(0, i)
        .reverse()
        .find(
          (c) =>
            c.amount === later.amount &&
            later.createdAt.getTime() - c.createdAt.getTime() <= HOUR
        );
      if (a) {
        const b = later;
        {
          const gap = gapText(b.createdAt.getTime() - a.createdAt.getTime());
          out.push({
            id: "duplicate_charge:" + later.id,
            kind: "duplicate_charge",
            title: "You were charged twice",
            detail: `Two charges of ${money(a.amount)} on ${shortDate(a.createdAt)} for order ${a.orderId ?? "—"}.`,
            evidence: [
              `Charge ${a.id} — ${money(a.amount)} — ${shortDate(a.createdAt)}`,
              `Charge ${b.id} — ${money(b.amount)} — ${gap} later`,
              a.orderId ? `Both point at order ${a.orderId}` : "No order attached to either charge",
            ],
            occurredAt: later.createdAt,
            baseScore: 0.9,
            variants: ["two charges","money twice","charged twice","charged double","extra back","twice card","charged again","double charge","two","charged","order","twice","charges","double"],
            action: {
              kind: "refund_duplicate",
              amount: later.amount,
              chargeId: later.id,
              orderId: a.orderId,
              summary: `Duplicate charge: ${a.id} and ${b.id}, both ${money(a.amount)}, ${gap} apart. Refunding ${later.id}.`,
            },
          });
        }
      }
    }
  }

  // late_delivery — 72 of 350 tickets; state present in 90; P(reason | state) = 0.8
  // Covers both observed shapes: still in transit past the promise, and
  // delivered after the promise within the last 7 days.
  for (const order of state.orders) {
    const stillMissing =
      now > order.promisedBy.getTime() &&
      order.status !== "delivered" &&
      order.status !== "cancelled";
    const arrivedLate =
      order.status === "delivered" &&
      order.deliveredAt &&
      order.deliveredAt.getTime() > order.promisedBy.getTime() &&
      now - order.deliveredAt.getTime() <= 7 * DAY;
    if (stillMissing) {
      out.push({
        id: "late_delivery:" + order.id,
        kind: "late_delivery",
        title: "Your order is late",
        detail: `Order ${order.id} was due ${shortDate(order.promisedBy)} and is still in transit.`,
        evidence: [
          `Order ${order.id} — placed ${shortDate(order.placedAt)}`,
          `Promised by ${shortDate(order.promisedBy)} — ${daysAgo(order.promisedBy)} days ago`,
          `Carrier status: ${order.status.replace("_", " ")}`,
        ],
        occurredAt: order.promisedBy,
        baseScore: 0.8,
        variants: [...["still waiting","where box","delivery date","order late","date tracking","order hasn","hasn t","date passed","order","where","late","still","waiting","date"], ...itemTokens(order)],
        action: {
          kind: "trace_shipment",
          orderId: order.id,
          summary: `Order ${order.id} promised ${shortDate(order.promisedBy)}, still ${order.status}. Opening a carrier trace.`,
        },
      });
    } else if (arrivedLate) {
      out.push({
        id: "late_delivery:" + order.id,
        kind: "late_delivery",
        title: "Your order arrived late",
        detail: `Order ${order.id} was due ${shortDate(order.promisedBy)} and arrived ${shortDate(order.deliveredAt!)}.`,
        evidence: [
          `Order ${order.id} — placed ${shortDate(order.placedAt)}`,
          `Promised by ${shortDate(order.promisedBy)}`,
          `Delivered ${shortDate(order.deliveredAt!)} — ${daysAgo(order.deliveredAt!)} days ago`,
        ],
        occurredAt: order.promisedBy,
        baseScore: 0.8,
        variants: [...["still waiting","where box","delivery date","order late","date tracking","order hasn","hasn t","date passed","order","where","late","still","waiting","date"], ...itemTokens(order)],
        action: {
          kind: "trace_shipment",
          orderId: order.id,
          summary: `Order ${order.id} arrived after its ${shortDate(order.promisedBy)} promise. Filing a late-delivery report.`,
        },
      });
    }
  }

  // refund_pending — 45 of 350 tickets; state present in 60; P(reason | state) = 0.75
  // Stale threshold 5 days: every cluster member was ≥6 days unsettled.
  for (const refund of state.refunds) {
    if (!refund.settledAt && now - refund.initiatedAt.getTime() > 5 * DAY) {
      out.push({
        id: "refund_pending:" + refund.id,
        kind: "refund_pending",
        title: "Your refund hasn't arrived",
        detail: `A refund of ${money(refund.amount)} was started ${daysAgo(refund.initiatedAt)} days ago.`,
        evidence: [
          `Refund ${refund.id} — ${money(refund.amount)}`,
          `Initiated ${shortDate(refund.initiatedAt)} — ${daysAgo(refund.initiatedAt)} days ago`,
          `Original charge ${refund.chargeId}`,
          "Not settled to the card yet",
        ],
        occurredAt: refund.initiatedAt,
        baseScore: 0.75,
        variants: ["money back","ago bank","nothing where","where money","been more","more nothing","still waiting","been over","refund","back","nothing","bank","been","still"],
        action: {
          kind: "expedite_refund",
          refundId: refund.id,
          amount: refund.amount,
          summary: `Refund ${refund.id} (${money(refund.amount)}) unsettled after ${daysAgo(refund.initiatedAt)} days. Escalating with the processor.`,
        },
      });
    }
  }

  // wrong_item — 112 of 350 tickets; state present in 160; P(reason | state) = 0.7
  // Contact window 14 days: p100 of delivery-to-contact gap in cluster was 12.
  for (const order of state.orders) {
    if (
      order.status === "delivered" &&
      order.deliveredAt &&
      now - order.deliveredAt.getTime() <= 14 * DAY
    ) {
      out.push({
        id: "wrong_item:" + order.id,
        kind: "wrong_item",
        title: "Something's wrong with what arrived",
        detail: `Order ${order.id} arrived ${daysAgo(order.deliveredAt)} days ago with the ${plainName(order)}.`,
        evidence: [
          `Order ${order.id} — delivered ${shortDate(order.deliveredAt)}`,
          ...order.items.map((i) => `${i.name} × ${i.qty}`),
          "Contact within 14 days of delivery",
        ],
        occurredAt: order.deliveredAt,
        baseScore: 0.7,
        variants: [...["thing arrived","arrived broken","water everywhere","side water","thing broke","broke crack","boily thing","glass everywhere","everywhere","water","broken","box","ordered","damaged"], ...itemTokens(order)],
        action: {
          kind: "open_replacement",
          orderId: order.id,
          summary: `Problem with delivered order ${order.id} (${plainName(order)}). Opening a replacement.`,
        },
      });
    }
  }

  // unexpected_renewal — 39 of 350 tickets; state present in 65; P(reason | state) = 0.6
  // Window 7 days: every cluster member renewed ≤6 days before contact.
  for (const sub of state.subscriptions) {
    if (sub.status === "active" && now - sub.renewedAt.getTime() <= 7 * DAY) {
      const plan = sub.planName.split(",")[0];
      out.push({
        id: "unexpected_renewal:" + sub.id,
        kind: "unexpected_renewal",
        title: "A subscription renewed",
        detail: `${plan} renewed on ${shortDate(sub.renewedAt)} for ${money(sub.amount)}.`,
        evidence: [
          `${sub.planName} — ${money(sub.amount)}`,
          `Renewed ${shortDate(sub.renewedAt)} — ${daysAgo(sub.renewedAt)} days ago`,
          `Subscribed since ${shortDate(sub.startedAt)}`,
        ],
        occurredAt: sub.renewedAt,
        baseScore: 0.6,
        variants: ["didn t","keeps taking","money again","took money","taking every","charged again","don t","t use","again","subscription","didn","charged","stop","keeps"],
        action: {
          kind: "refund_renewal",
          subscriptionId: sub.id,
          amount: sub.amount,
          summary: `Unexpected renewal of ${sub.planName} (${money(sub.amount)}). Refunding and pausing the subscription.`,
        },
      });
    }
  }

  return out;
}
