/**
 * AUTO-GENERATED by scripts/generate-rules.ts. Do not edit by hand.
 *
 * This file records offline provenance only. Runtime hypothesis generation is
 * implemented in hypotheses.generated.ts and never reads the synthetic corpus.
 */
export const RULE_PROVENANCE = {
  schemaVersion: "wordless-rule-provenance.v1",
  generationMode: "deterministic-offline",
  runtimeCorpusDependency: false,
  corpusSeed: "0x574F5244",
  corpusSnapshotAt: "2026-04-15T12:00:00.000Z",
  corpusSha256: "d6ec7895137f517fa3b9aafa91166a15447238808a57be4d0a155f1f958d030d",
  typesSha256: "aeb4c0237d1e0a61b90111d0602a6ce24a18f8327055b10f2e14057194e6468c",
  detectorSourceSha256: "6cba73dd4da587a1cf7121c33fd0bba1fbc0fcf35080a1f49d522d14290d39bc",
  totalRecords: 384,
  rules: [
    {
      resolutionKind: "duplicate_charge",
      detectorKind: "duplicate_charge",
      actionKind: "refund_duplicate",
      recordCount: 64,
      styles: {"fragment":16,"misspelling":16,"circumlocution":16,"fluent":16},
    },
    {
      resolutionKind: "wrong_item",
      detectorKind: "wrong_item",
      actionKind: "replace_item",
      recordCount: 64,
      styles: {"fragment":16,"misspelling":16,"circumlocution":16,"fluent":16},
    },
    {
      resolutionKind: "late_delivery",
      detectorKind: "late_delivery",
      actionKind: "trace_delivery",
      recordCount: 64,
      styles: {"fragment":16,"misspelling":16,"circumlocution":16,"fluent":16},
    },
    {
      resolutionKind: "unexpected_renewal",
      detectorKind: "unexpected_renewal",
      actionKind: "review_renewal",
      recordCount: 64,
      styles: {"fragment":16,"misspelling":16,"circumlocution":16,"fluent":16},
    },
    {
      resolutionKind: "refund_pending",
      detectorKind: "refund_pending",
      actionKind: "trace_refund",
      recordCount: 64,
      styles: {"fragment":16,"misspelling":16,"circumlocution":16,"fluent":16},
    },
    {
      resolutionKind: "clean_state",
      detectorKind: null,
      actionKind: null,
      recordCount: 64,
      styles: {"fragment":16,"misspelling":16,"circumlocution":16,"fluent":16},
    },
  ],
} as const;
