import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const expectedRules = [
  {
    resolutionKind: "duplicate_charge",
    detectorKind: "duplicate_charge",
    actionKind: "refund_duplicate",
  },
  {
    resolutionKind: "wrong_item",
    detectorKind: "wrong_item",
    actionKind: "replace_item",
  },
  {
    resolutionKind: "late_delivery",
    detectorKind: "late_delivery",
    actionKind: "trace_delivery",
  },
  {
    resolutionKind: "unexpected_renewal",
    detectorKind: "unexpected_renewal",
    actionKind: "review_renewal",
  },
  {
    resolutionKind: "refund_pending",
    detectorKind: "refund_pending",
    actionKind: "trace_refund",
  },
  {
    resolutionKind: "clean_state",
    detectorKind: null,
    actionKind: null,
  },
] as const;

const expectedStyles = [
  "fragment",
  "misspelling",
  "circumlocution",
  "fluent",
] as const;

type ResolutionKind = (typeof expectedRules)[number]["resolutionKind"];
type Style = (typeof expectedStyles)[number];

interface CorpusRecord {
  ticketId: string;
  fictional: boolean;
  style: string;
  customerText: { subject: string; body: string };
  accountStateAtContact: {
    email: string;
    orders: unknown[];
    charges: unknown[];
    subscriptions: unknown[];
    refunds: unknown[];
    priorTickets: unknown[];
  };
  expectedResolution: {
    kind: string;
    detectorKind: string | null;
    actionKind: string | null;
    summary: string;
  };
}

interface CorpusDocument {
  schemaVersion: string;
  seed: string;
  fixedSnapshotAt: string;
  records: CorpusRecord[];
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`Rule generation validation failed: ${message}`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function parseCorpus(source: string): CorpusDocument {
  const parsed: unknown = JSON.parse(source);
  assert(isRecord(parsed), "corpus root must be an object");
  assert(parsed.schemaVersion === "wordless-ticket-corpus.v1", "unexpected corpus schema version");
  assert(typeof parsed.seed === "string", "corpus seed is missing");
  assert(typeof parsed.fixedSnapshotAt === "string", "fixed snapshot is missing");
  assert(Array.isArray(parsed.records), "corpus records must be an array");
  return parsed as unknown as CorpusDocument;
}

function countBy<T extends string>(values: readonly T[]): Record<T, number> {
  return values.reduce(
    (counts, value) => {
      counts[value] += 1;
      return counts;
    },
    Object.fromEntries([...new Set(values)].map((value) => [value, 0])) as Record<T, number>,
  );
}

function quote(value: string | null): string {
  return value === null ? "null" : JSON.stringify(value);
}

function renderProvenance(input: {
  corpusSha256: string;
  typesSha256: string;
  detectorSourceSha256: string;
  totalRecords: number;
  seed: string;
  fixedSnapshotAt: string;
  ruleRows: Array<{
    resolutionKind: ResolutionKind;
    detectorKind: string | null;
    actionKind: string | null;
    count: number;
    styles: Record<Style, number>;
  }>;
}): string {
  const rows = input.ruleRows
    .map(
      (row) => `    {
      resolutionKind: ${JSON.stringify(row.resolutionKind)},
      detectorKind: ${quote(row.detectorKind)},
      actionKind: ${quote(row.actionKind)},
      recordCount: ${row.count},
      styles: ${JSON.stringify(row.styles)},
    },`,
    )
    .join("\n");

  return `/**
 * AUTO-GENERATED by scripts/generate-rules.ts. Do not edit by hand.
 *
 * This file records offline provenance only. Runtime hypothesis generation is
 * implemented in hypotheses.generated.ts and never reads the synthetic corpus.
 */
export const RULE_PROVENANCE = {
  schemaVersion: "wordless-rule-provenance.v1",
  generationMode: "deterministic-offline",
  runtimeCorpusDependency: false,
  corpusSeed: ${JSON.stringify(input.seed)},
  corpusSnapshotAt: ${JSON.stringify(input.fixedSnapshotAt)},
  corpusSha256: ${JSON.stringify(input.corpusSha256)},
  typesSha256: ${JSON.stringify(input.typesSha256)},
  detectorSourceSha256: ${JSON.stringify(input.detectorSourceSha256)},
  totalRecords: ${input.totalRecords},
  rules: [
${rows}
  ],
} as const;
`;
}

async function main(): Promise<void> {
  const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
  const projectRoot = path.resolve(scriptDirectory, "..");
  const corpusPath = path.join(projectRoot, "data/ticket-corpus.json");
  const typesPath = path.join(projectRoot, "lib/types.ts");
  const detectorsPath = path.join(projectRoot, "lib/hypotheses.generated.ts");

  const [corpusSource, typesSource, detectorSource] = await Promise.all([
    readFile(corpusPath, "utf8"),
    readFile(typesPath, "utf8"),
    readFile(detectorsPath, "utf8"),
  ]);
  const corpus = parseCorpus(corpusSource);

  assert(corpus.records.length >= 360, "corpus must contain at least 360 records");
  assert(typesSource.includes("export interface AccountState"), "lib/types.ts must define AccountState");
  assert(typesSource.includes("export type ActionSpec"), "lib/types.ts must define ActionSpec");
  assert(detectorSource.includes("export function generateHypotheses"), "detector catalogue must export generateHypotheses");

  const ticketIds = new Set<string>();
  const resolutionCounts = Object.fromEntries(
    expectedRules.map((rule) => [rule.resolutionKind, 0]),
  ) as Record<ResolutionKind, number>;
  const styleCounts = Object.fromEntries(
    expectedRules.map((rule) => [
      rule.resolutionKind,
      Object.fromEntries(expectedStyles.map((style) => [style, 0])),
    ]),
  ) as Record<ResolutionKind, Record<Style, number>>;

  for (const [index, record] of corpus.records.entries()) {
    const location = `record ${index + 1}`;
    assert(typeof record.ticketId === "string" && record.ticketId.length > 0, `${location} needs a ticketId`);
    assert(!ticketIds.has(record.ticketId), `${location} repeats ticketId ${record.ticketId}`);
    ticketIds.add(record.ticketId);
    assert(record.fictional === true, `${record.ticketId} must be explicitly fictional`);
    assert(record.accountStateAtContact.email.endsWith("@example.invalid"), `${record.ticketId} must use the reserved fictional email domain`);
    assert(typeof record.customerText.subject === "string" && record.customerText.subject.length > 0, `${record.ticketId} needs a subject`);
    assert(typeof record.customerText.body === "string" && record.customerText.body.length > 0, `${record.ticketId} needs a body`);

    const expected = expectedRules.find((rule) => rule.resolutionKind === record.expectedResolution.kind);
    assert(expected, `${record.ticketId} has unknown resolution kind ${record.expectedResolution.kind}`);
    assert(record.expectedResolution.detectorKind === expected.detectorKind, `${record.ticketId} has the wrong detector mapping`);
    assert(record.expectedResolution.actionKind === expected.actionKind, `${record.ticketId} has the wrong action mapping`);
    assert(typeof record.expectedResolution.summary === "string" && record.expectedResolution.summary.length > 0, `${record.ticketId} needs a resolution summary`);
    assert(expectedStyles.includes(record.style as Style), `${record.ticketId} has unknown language style ${record.style}`);

    const kind = expected.resolutionKind;
    const style = record.style as Style;
    resolutionCounts[kind] += 1;
    styleCounts[kind][style] += 1;
  }

  for (const rule of expectedRules) {
    assert(resolutionCounts[rule.resolutionKind] >= 60, `${rule.resolutionKind} needs at least 60 records`);
    for (const style of expectedStyles) {
      assert(styleCounts[rule.resolutionKind][style] >= 12, `${rule.resolutionKind} needs at least 12 ${style} records`);
    }

    if (rule.detectorKind === null) {
      assert(!detectorSource.includes('kind: "clean_state"'), "clean_state must not manufacture a runtime hypothesis");
    } else {
      assert(detectorSource.includes(`kind: "${rule.detectorKind}"`), `runtime detector ${rule.detectorKind} is missing`);
    }

    if (rule.actionKind !== null) {
      assert(typesSource.includes(`kind: "${rule.actionKind}"`), `ActionSpec kind ${rule.actionKind} is missing`);
    }
  }

  const ruleRows = expectedRules.map((rule) => ({
    ...rule,
    count: resolutionCounts[rule.resolutionKind],
    styles: styleCounts[rule.resolutionKind],
  }));
  const hashes = {
    corpusSha256: sha256(corpusSource),
    typesSha256: sha256(typesSource),
    detectorSourceSha256: sha256(detectorSource),
  };

  const report = {
    schemaVersion: "wordless-rule-generation-report.v1",
    generator: "scripts/generate-rules.ts",
    mode: "deterministic-offline",
    networkAccess: "none",
    runtimeCorpusDependency: false,
    status: "passed",
    inputs: {
      corpus: "data/ticket-corpus.json",
      types: "lib/types.ts",
      detectorCatalogue: "lib/hypotheses.generated.ts",
      corpusSeed: corpus.seed,
      fixedSnapshotAt: corpus.fixedSnapshotAt,
      ...hashes,
    },
    validation: {
      minimumRecords: 360,
      totalRecords: corpus.records.length,
      uniqueTicketIds: ticketIds.size,
      allRecordsExplicitlyFictional: true,
      fictionalEmailDomain: "example.invalid",
      expectedStyles,
      rules: ruleRows,
      checks: [
        "corpus schema and mappings",
        "minimum records per resolution kind",
        "language-style coverage per resolution kind",
        "ActionSpec literals in lib/types.ts",
        "detector literals in lib/hypotheses.generated.ts",
        "clean-state non-detector invariant",
      ],
    },
    outputs: {
      provenance: "lib/rule-provenance.generated.ts",
      report: "data/rule-generation-report.json",
    },
  };

  await mkdir(path.join(projectRoot, "data"), { recursive: true });
  await Promise.all([
    writeFile(
      path.join(projectRoot, "lib/rule-provenance.generated.ts"),
      renderProvenance({
        ...hashes,
        totalRecords: corpus.records.length,
        seed: corpus.seed,
        fixedSnapshotAt: corpus.fixedSnapshotAt,
        ruleRows,
      }),
      "utf8",
    ),
    writeFile(
      path.join(projectRoot, "data/rule-generation-report.json"),
      `${JSON.stringify(report, null, 2)}\n`,
      "utf8",
    ),
  ]);

  const styleTotals = countBy(corpus.records.map((record) => record.style));
  process.stdout.write(
    `Validated ${corpus.records.length} tickets; wrote deterministic provenance and report. Styles: ${JSON.stringify(styleTotals)}\n`,
  );
}

await main();
